name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: abinnovision/actions/actions/setup-node@master

      - name: Install dependencies
        run: yarn install --immutable

      # Lint & Format
      - name: Check
        run: yarn check

      # Build
      - name: Build
        run: yarn build

  test-e2e:
    name: E2E Tests (Cypress)
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: abinnovision/actions/actions/setup-node@master

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cypress (Chrome)
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
